-- MariaDB dump 10.19  Distrib 10.4.32-MariaDB, for Win64 (AMD64)
--
-- Host: localhost    Database: db11x11
-- ------------------------------------------------------
-- Server version	10.4.32-MariaDB

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Dumping data for table `posts`
--

/*!40000 ALTER TABLE `posts` DISABLE KEYS */;
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (5,'Родри перешел из «Манчестер Сити» в «Барселону»','Rodri completes move to Barcelona from Manchester City',NULL,'Контракт рассчитан до июня 2030-го года...','The contract runs until June 2030...','Контракт рассчитан до июня 2030-го года...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/eng/news/168395/rodri-completes-move-to-barcelona-from-manchester-city.html','The contract runs until June 2030...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/eng/news/168395/rodri-completes-move-to-barcelona-from-manchester-city.html','laliga','https://sport.news.am/static/news/b/2026/08/168395.jpg','published',NULL,1,5,'2026-08-18 19:32:06','2026-08-18 19:52:24','2026-08-18 17:03:00');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (6,'Патрик Виейра возглавил сборную Сенегала','Patrick Vieira named Senegal manager',NULL,'50-летний французский специалист...','A World and European champion as a player...','50-летний французский специалист...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/eng/news/168390/patrick-vieira-named-senegal-manager.html','A World and European champion as a player...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/eng/news/168390/patrick-vieira-named-senegal-manager.html','national','https://sport.news.am/static/news/b/2026/08/168390.jpg','published',NULL,1,2,'2026-08-18 19:32:06','2026-08-18 19:42:52','2026-08-18 13:38:00');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (7,'«Арарат-Армения» провел заключительную тренировку перед вылетом в Румынию','Ararat-Armenia final training before travelling to Craiova',NULL,'В Ереване...','In Yerevan...','В Ереване...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/eng/news/168387/ararat-armenia-final-training-before-travelling-to-craiova.html','In Yerevan...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/eng/news/168387/ararat-armenia-final-training-before-travelling-to-craiova.html','armenia','https://sport.news.am/static/news/b/2026/08/168387.jpg','published',NULL,1,1,'2026-08-18 19:32:06','2026-08-18 19:39:54','2026-08-18 12:33:00');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (8,'Ararat-Armenia congratulates Samvel Karapetyan','Ararat-Armenia congratulates Samvel Karapetyan',NULL,'The club’s founder and owner...','The club’s founder and owner...','The club’s founder and owner...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/eng/news/168386/ararat-armenia-congratulates-samvel-karapetyan.html','The club’s founder and owner...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/eng/news/168386/ararat-armenia-congratulates-samvel-karapetyan.html','armenia','https://sport.news.am/static/news/b/2026/08/168386.jpg','published',NULL,1,1,'2026-08-18 19:32:06','2026-08-18 19:52:44','2026-08-18 12:02:00');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (9,'Топ-10 претендентов на Golden Boy','Top-10 Golden Boy nominees',NULL,'Первое место занимает Пау Кубарси...','Pau Cubarsi (Barcelona)...','Первое место занимает Пау Кубарси...\r\n\r\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/eng/news/168383/top-10-golden-boy-nominees.html','Pau Cubarsi (Barcelona)...\r\n\r\nSource: NEWS.am Sport — read the full article: https://sport.news.am/eng/news/168383/top-10-golden-boy-nominees.html','laliga','https://sport.news.am/static/news/b/2026/08/168383.jpg','published',NULL,1,2,'2026-08-18 19:32:06','2026-08-18 19:43:00','2026-08-18 10:05:00');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (10,'«Олимпиакос» подписал 4-летний контракт с Тикнизяном','Olympiacos signed a four-year contract with Nair Tiknizyan',NULL,'27-летний защитник сборной Армении...','Nair Tiknizyan\'s annual salary will be €1.1 million...','27-летний защитник сборной Армении...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/eng/news/168380/olympiacos-signed-a-four-year-contract-with-nair-tiknizyan.html','Nair Tiknizyan\'s annual salary will be €1.1 million...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/eng/news/168380/olympiacos-signed-a-four-year-contract-with-nair-tiknizyan.html','armenia','https://sport.news.am/static/news/b/2026/08/168380.jpg','published',NULL,1,0,'2026-08-18 19:32:06','2026-08-18 19:38:56','2026-08-18 07:43:00');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (11,'Harry Kane: Of course, it would be wonderful to win the Ballon d\'Or','Harry Kane: Of course, it would be wonderful to win the Ballon d\'Or',NULL,'I am proud of the results achieved with Bayern and the England national team...','I am proud of the results achieved with Bayern and the England national team...','I am proud of the results achieved with Bayern and the England national team...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/eng/news/168379/harry-kane-of-course-it-would-be-wonderful-to-win-the-ballon-dor.html','I am proud of the results achieved with Bayern and the England national team...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/eng/news/168379/harry-kane-of-course-it-would-be-wonderful-to-win-the-ballon-dor.html','national','https://sport.news.am/static/news/b/2026/08/168379.jpg','published',NULL,1,1,'2026-08-18 19:32:06','2026-08-18 19:39:44','2026-08-18 07:07:00');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (12,'Наир Тикнизян - игрок «Олимпиакоса»','Nair Tiknizyan is an Olympiacos player',NULL,'27-летний защитник сборной Армении...','The 27-year-old midfielder of the Armenian national team...','27-летний защитник сборной Армении...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/eng/news/168378/nair-tiknizyan-is-an-olympiacos-player.html','The 27-year-old midfielder of the Armenian national team...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/eng/news/168378/nair-tiknizyan-is-an-olympiacos-player.html','armenia','https://sport.news.am/static/news/b/2026/08/168378.jpg','published',NULL,1,0,'2026-08-18 19:32:06','2026-08-18 19:38:56','2026-08-18 06:55:00');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (13,'Победа «Аль-Ахли», Сперцян отличился во втором матче подряд (видео)','Al-Ahli victory, Spertsyan scored in his second consecutive match',NULL,'Кубок Короля Саудовской Аравии...','Saudi King\'s Cup...','Кубок Короля Саудовской Аравии...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/eng/news/168374/al-ahli-victory-spertsyan-scored-in-his-second-consecutive-match.html','Saudi King\'s Cup...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/eng/news/168374/al-ahli-victory-spertsyan-scored-in-his-second-consecutive-match.html','armenia','https://sport.news.am/static/news/b/2026/08/168374.jpg','published',NULL,1,0,'2026-08-18 19:32:06','2026-08-18 19:38:56','2026-08-17 18:05:00');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (14,'«Ноа» оказался сильнее «Алашкерта» (видео)','Noah beat Alashkert',NULL,'Чемпионат Армении...','1-0...','Чемпионат Армении...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/eng/news/168373/noah-beat-alashkert.html','1-0...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/eng/news/168373/noah-beat-alashkert.html','armenia','https://sport.news.am/static/news/b/2026/08/168373.jpg','published',NULL,1,0,'2026-08-18 19:32:06','2026-08-18 19:38:56','2026-08-17 17:56:00');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (15,'Томас Мюллер забил гол во втором матче МЛС подряд (видео)','Thomas Muller scored in the second consecutive MLS match',NULL,'Легендарный нападающий мюнхенской «Баварии»...','Legendary Bayern Munich forward...','Легендарный нападающий мюнхенской «Баварии»...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/eng/news/168369/thomas-muller-scored-in-the-second-consecutive-mls-match.html','Legendary Bayern Munich forward...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/eng/news/168369/thomas-muller-scored-in-the-second-consecutive-mls-match.html','news','https://sport.news.am/static/news/b/2026/08/168369.jpg','published',NULL,1,0,'2026-08-18 19:32:06','2026-08-18 19:38:56','2026-08-17 14:11:00');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (16,'Ararat-Armenia to the fans: We need your support','Ararat-Armenia to the fans: We need your support',NULL,'TOGETHER WE CAN...','TOGETHER WE CAN...','TOGETHER WE CAN...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/eng/news/168365/ararat-armenia-to-the-fans-we-need-your-support.html','TOGETHER WE CAN...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/eng/news/168365/ararat-armenia-to-the-fans-we-need-your-support.html','armenia','https://sport.news.am/static/news/b/2026/08/168365.jpg','published',NULL,1,0,'2026-08-18 19:32:06','2026-08-18 19:38:56','2026-08-17 12:12:00');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (17,'«Ювентус» подписал защитника сборной Колумбии','Jhon Lucumi joins Juventus',NULL,'Джон Лукуми…','Colombia national team and Bologna defender...','Джон Лукуми…\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/eng/news/168360/jhon-lucumi-joins-juventus.html','Colombia national team and Bologna defender...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/eng/news/168360/jhon-lucumi-joins-juventus.html','seriea','https://sport.news.am/static/news/b/2026/08/168360.jpg','published',NULL,1,0,'2026-08-18 19:32:06','2026-08-18 19:38:56','2026-08-17 10:02:00');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (18,'Мареска: Пропущенный на первой минуте гол повлиял на ход игры','Maresca: I feel disappointed, the early goal affected us',NULL,'Нам предстоит еще много работать...','Manchester City head coach...','Нам предстоит еще много работать...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/eng/news/168357/maresca-i-feel-disappointed-the-early-goal-affected-us.html','Manchester City head coach...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/eng/news/168357/maresca-i-feel-disappointed-the-early-goal-affected-us.html','epl','https://sport.news.am/static/news/b/2026/08/168357.jpg','published',NULL,1,0,'2026-08-18 19:32:06','2026-08-18 19:38:56','2026-08-17 08:19:00');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (19,'«Барселона» представит Родри на этой неделе','Barcelona will present Rodri this week',NULL,'Сумма трансфера 30-летнего футболиста сборной Испании составит 76,5 млн евро...','Manchester City midfielder...','Сумма трансфера 30-летнего футболиста сборной Испании составит 76,5 млн евро...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/eng/news/168355/barcelona-will-present-rodri-this-week.html','Manchester City midfielder...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/eng/news/168355/barcelona-will-present-rodri-this-week.html','laliga','https://sport.news.am/static/news/b/2026/08/168355.jpg','published',NULL,1,0,'2026-08-18 19:32:06','2026-08-18 19:38:56','2026-08-17 07:05:00');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (20,'Sebastien Pocognoli confirmed as new Scotland boss','Sebastien Pocognoli confirmed as new Scotland boss',NULL,'The 39-year-old Belgian coach has signed a two-year contract...','The 39-year-old Belgian coach has signed a two-year contract...','The 39-year-old Belgian coach has signed a two-year contract...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/eng/news/168353/sebastien-pocognoli-confirmed-as-new-scotland-boss.html','The 39-year-old Belgian coach has signed a two-year contract...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/eng/news/168353/sebastien-pocognoli-confirmed-as-new-scotland-boss.html','national','https://sport.news.am/static/news/b/2026/08/168353.jpg','published',NULL,1,0,'2026-08-18 19:32:06','2026-08-18 19:38:56','2026-08-17 06:24:00');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (21,'Mourinho explains his black eye','Mourinho explains his black eye',NULL,'Real Madrid head coach...','Real Madrid head coach...','Real Madrid head coach...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/eng/news/168352/mourinho-explains-his-black-eye.html','Real Madrid head coach...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/eng/news/168352/mourinho-explains-his-black-eye.html','laliga','https://sport.news.am/static/news/b/2026/08/168352.jpg','published',NULL,1,0,'2026-08-18 19:32:06','2026-08-18 19:38:56','2026-08-17 05:17:00');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (22,'French Super Cup: Lens defeated PSG','French Super Cup: Lens defeated PSG',NULL,'1–0...','1–0...','1–0...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/eng/news/168354/french-super-cup-lens-defeated-psg.html','1–0...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/eng/news/168354/french-super-cup-lens-defeated-psg.html','ligue1','https://sport.news.am/static/news/b/2026/08/168354.jpg','published',NULL,1,0,'2026-08-18 19:32:06','2026-08-18 19:38:56','2026-08-16 20:49:00');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (23,'Atletico Madrid defeat Marseille','Atletico Madrid defeat Marseille',NULL,'2–1...','2–1...','2–1...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/eng/news/168323/atletico-madrid-defeat-marseille.html','2–1...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/eng/news/168323/atletico-madrid-defeat-marseille.html','laliga','https://sport.news.am/static/news/b/2026/08/168323.jpg','published',NULL,1,0,'2026-08-18 19:32:06','2026-08-18 19:38:56','2026-08-14 17:32:00');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (24,'Albert Riera – Crvena Zvezda head coach','Albert Riera – Crvena Zvezda head coach',NULL,'The 44-year-old Spanish coach has signed a contract with the club until 2029...','The 44-year-old Spanish coach has signed a contract with the club until 2029...','The 44-year-old Spanish coach has signed a contract with the club until 2029...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/eng/news/168319/albert-rieracrvena-zvezda-head-coach.html','The 44-year-old Spanish coach has signed a contract with the club until 2029...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/eng/news/168319/albert-rieracrvena-zvezda-head-coach.html','transfers','https://sport.news.am/static/news/b/2026/08/168319.jpg','published',NULL,1,0,'2026-08-18 19:32:06','2026-08-18 19:38:56','2026-08-14 13:19:00');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (25,'Луис Энрике - о поражении ПСЖ: Наш уровень превзошел мои ожидания','Луис Энрике - о поражении ПСЖ: Наш уровень превзошел мои ожидания',NULL,'Мы провели очень хороший матч…','Мы провели очень хороший матч…','Мы провели очень хороший матч…\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/rus/news/football/','Мы провели очень хороший матч…\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/rus/news/football/','ligue1','https://sport.news.am/static/news/b/2026/08/168359.jpg','published',NULL,1,1,'2026-08-18 19:32:06','2026-08-18 19:40:07','2026-08-18 12:32:06');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (26,'Наир Тикнизян прибыл в Грецию и подпишет контракт с «Олимпиакосом»','Наир Тикнизян прибыл в Грецию и подпишет контракт с «Олимпиакосом»',NULL,'Защитник сборной Армении…','Защитник сборной Армении…','Защитник сборной Армении…\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/rus/news/football/','Защитник сборной Армении…\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/rus/news/football/','armenia','https://sport.news.am/static/news/b/2026/08/168362.jpg','published',NULL,1,0,'2026-08-18 19:32:06','2026-08-18 19:38:56','2026-08-18 12:17:06');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (27,'Серхио Бускетс вернулся в «Барселону»','Серхио Бускетс вернулся в «Барселону»',NULL,'В качестве тренера...','В качестве тренера...','В качестве тренера...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/rus/news/football/','В качестве тренера...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/rus/news/football/','laliga','https://sport.news.am/static/news/b/2026/08/168368.jpg','published',NULL,1,1,'2026-08-18 19:32:06','2026-08-18 19:40:15','2026-08-18 12:02:06');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (28,'Родри прибыл в Барселону (видео)','Родри прибыл в Барселону (видео)',NULL,'Я счастлив...','Я счастлив...','Я счастлив...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/rus/news/football/','Я счастлив...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/rus/news/football/','laliga','https://sport.news.am/static/news/b/2026/08/168375.jpg','published',NULL,1,1,'2026-08-18 19:32:06','2026-08-18 19:41:15','2026-08-18 11:47:06');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (29,'«Реал» представил Моуринью: Это как возвращение домой','«Реал» представил Моуринью: Это как возвращение домой',NULL,'Сейчас волнуюсь даже больше, чем в момент первого прихода...','Сейчас волнуюсь даже больше, чем в момент первого прихода...','Сейчас волнуюсь даже больше, чем в момент первого прихода...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/rus/news/football/','Сейчас волнуюсь даже больше, чем в момент первого прихода...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/rus/news/football/','laliga','https://sport.news.am/static/news/b/2026/08/168388.jpg','published',NULL,1,0,'2026-08-18 19:32:06','2026-08-18 19:38:56','2026-08-18 11:32:06');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (30,'Названы лучшие центральные нападающие мира','Названы лучшие центральные нападающие мира',NULL,'По версии ESPN...','По версии ESPN...','По версии ESPN...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/rus/news/football/','По версии ESPN...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/rus/news/football/','news','https://sport.news.am/static/news/b/2026/08/168389.jpg','published',NULL,1,1,'2026-08-18 19:32:06','2026-08-18 19:41:05','2026-08-18 11:17:06');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (31,'Названы лучшие вингеры мира','Названы лучшие вингеры мира',NULL,'Футболист «Баварии» и сборной Франции Майкл Олисе...','Футболист «Баварии» и сборной Франции Майкл Олисе...','Футболист «Баварии» и сборной Франции Майкл Олисе...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/rus/news/football/','Футболист «Баварии» и сборной Франции Майкл Олисе...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/rus/news/football/','national','https://sport.news.am/static/news/b/2026/08/168392.jpg','published',NULL,1,0,'2026-08-18 19:32:06','2026-08-18 19:38:56','2026-08-18 11:02:06');
INSERT INTO `posts` (`id`, `title`, `title_en`, `slug`, `excerpt`, `excerpt_en`, `body`, `body_en`, `category`, `cover_url`, `status`, `reject_note`, `author_id`, `views`, `created_at`, `updated_at`, `published_at`) VALUES (32,'Наир Тикнизян не сдержал слез, прощаясь с игроками «Црвены Звезды» (видео)','Наир Тикнизян не сдержал слез, прощаясь с игроками «Црвены Звезды» (видео)',NULL,'Я плачу, потому что всегда был искренен...','Я плачу, потому что всегда был искренен...','Я плачу, потому что всегда был искренен...\n\nИсточник: NEWS.am Sport — полный текст: https://sport.news.am/rus/news/football/','Я плачу, потому что всегда был искренен...\n\nSource: NEWS.am Sport — read the full article: https://sport.news.am/rus/news/football/','armenia','https://sport.news.am/static/news/b/2026/08/168394.jpg','published',NULL,1,1,'2026-08-18 19:32:06','2026-08-18 19:43:10','2026-08-18 10:47:06');
/*!40000 ALTER TABLE `posts` ENABLE KEYS */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2026-08-18 23:53:30
